#!/usr/bin/env python3
import argparse, ctypes, math, mmap, os, sys
import numpy as np
from fcntl import ioctl

sys.path.insert(0, os.path.join(os.path.dirname(__file__), "..", "experimental"))
import rockchip as rk  # noqa: E402


LUT_SIZE = 513
RKNPU_MEM_KERNEL_MAPPING = 8
RKNPU_MEM_NON_CACHEABLE = 0
RKNPU_ACT_RESET = 1
RKNPU_JOB_PC = 0x1
RKNPU_JOB_BLOCK = 0x2
RKNPU_JOB_PINGPONG = 0x4


class rknpu_mem_create(ctypes.Structure):
  _fields_ = [
    ("handle", ctypes.c_uint32),
    ("flags", ctypes.c_uint32),
    ("size", ctypes.c_uint64),
    ("obj_addr", ctypes.c_uint64),
    ("dma_addr", ctypes.c_uint64),
    ("sram_size", ctypes.c_uint64),
  ]


class rknpu_mem_map(ctypes.Structure):
  _fields_ = [
    ("handle", ctypes.c_uint32),
    ("reserved", ctypes.c_uint32),
    ("offset", ctypes.c_uint64),
  ]


class rknpu_subcore_task(ctypes.Structure):
  _fields_ = [("task_start", ctypes.c_uint32), ("task_number", ctypes.c_uint32)]


class rknpu_submit(ctypes.Structure):
  _fields_ = [
    ("flags", ctypes.c_uint32),
    ("timeout", ctypes.c_uint32),
    ("task_start", ctypes.c_uint32),
    ("task_number", ctypes.c_uint32),
    ("task_counter", ctypes.c_uint32),
    ("priority", ctypes.c_int32),
    ("task_obj_addr", ctypes.c_uint64),
    ("regcfg_obj_addr", ctypes.c_uint64),
    ("task_base_addr", ctypes.c_uint64),
    ("user_data", ctypes.c_uint64),
    ("core_mask", ctypes.c_uint32),
    ("fence_fd", ctypes.c_int32),
    ("subcore_task", rknpu_subcore_task * 5),
  ]


class rknpu_action(ctypes.Structure):
  _fields_ = [("flags", ctypes.c_uint32), ("value", ctypes.c_uint32)]


class struct_rknpu_task(ctypes.Structure):
  _fields_ = [
    ("flags", ctypes.c_uint32),
    ("op_idx", ctypes.c_uint32),
    ("enable_mask", ctypes.c_uint32),
    ("int_mask", ctypes.c_uint32),
    ("int_clear", ctypes.c_uint32),
    ("int_status", ctypes.c_uint32),
    ("regcfg_amount", ctypes.c_uint32),
    ("regcfg_offset", ctypes.c_uint32),
    ("regcmd_addr", ctypes.c_uint64),
  ]


def _IOWR(type_, nr, size):
  return (3 << 30) | (ord(type_) << 8) | (nr << 0) | (size << 16)


DRM_IOCTL_RKNPU_MEM_CREATE = _IOWR("d", 0x42, ctypes.sizeof(rknpu_mem_create))
DRM_IOCTL_RKNPU_MEM_MAP = _IOWR("d", 0x43, ctypes.sizeof(rknpu_mem_map))
DRM_IOCTL_RKNPU_SUBMIT = _IOWR("d", 0x41, ctypes.sizeof(rknpu_submit))
DRM_IOCTL_RKNPU_ACTION = _IOWR("d", 0x40, ctypes.sizeof(rknpu_action))


def mem_allocate(fd, size, flags=0):
  mem_create = rknpu_mem_create(flags=flags, size=size)
  ioctl(fd, DRM_IOCTL_RKNPU_MEM_CREATE, mem_create)
  mem_map = rknpu_mem_map(handle=mem_create.handle)
  ioctl(fd, DRM_IOCTL_RKNPU_MEM_MAP, mem_map)
  buf = mmap.mmap(fd, mem_create.size, mmap.MAP_SHARED, mmap.PROT_READ | mmap.PROT_WRITE, offset=mem_map.offset)
  return buf, mem_create


def submit(fd, task_obj_addr):
  submit_struct = rknpu_submit(
    flags=RKNPU_JOB_PC | RKNPU_JOB_BLOCK | RKNPU_JOB_PINGPONG,
    timeout=6000,
    task_start=0,
    task_number=1,
    task_counter=0,
    priority=0,
    task_obj_addr=task_obj_addr,
    regcfg_obj_addr=0,
    task_base_addr=0,
    user_data=0,
    core_mask=1,
    fence_fd=-1,
  )
  submit_struct.subcore_task[0] = rknpu_subcore_task(task_start=0, task_number=1)
  submit_struct.subcore_task[1] = rknpu_subcore_task(task_start=1, task_number=0)
  submit_struct.subcore_task[2] = rknpu_subcore_task(task_start=2, task_number=0)
  submit_struct.subcore_task[3] = rknpu_subcore_task(task_start=0, task_number=0)
  submit_struct.subcore_task[4] = rknpu_subcore_task(task_start=0, task_number=0)
  return ioctl(fd, DRM_IOCTL_RKNPU_SUBMIT, submit_struct)


def reset_npu(fd):
  return ioctl(fd, DRM_IOCTL_RKNPU_ACTION, rknpu_action(flags=RKNPU_ACT_RESET, value=0))


def reg(val, shift, mask):
  return (int(val) << shift) & mask


def emit(target, addr, value):
  # The autogenerated rk.PC target does not match the examples' packed PC target.
  if target == rk.PC: target = 0x80
  return (((target + 1) & 0xffff) << 48) | ((int(value) & 0xffffffff) << 16) | (addr & 0xffff)


def make_silu_lut():
  # Mirrors experimental/rknnops.h's alu_case_silu LUT construction.
  lut = [0] * (LUT_SIZE * 2)
  index_scale = 2824.0
  step = 32.0 / index_scale
  output_scale = 5664.8

  for i in range(LUT_SIZE):
    x = (LUT_SIZE - 1 - i) * step
    y = -x / (1.0 + math.exp(x))
    lut[i] = int(np.clip(round(y * output_scale), -32768, 32767))
  for i in range(LUT_SIZE):
    x = i * step
    y = x / (1.0 + math.exp(-x))
    lut[LUT_SIZE + i] = int(np.clip(round(y * output_scale), -32768, 32767))

  return lut, 0x6984, output_scale, index_scale


def fill_lut_regs(lut):
  regs = []
  for table_id, base in ((0, 0), (1, LUT_SIZE)):
    regs.append(emit(rk.DPU, rk.REG_DPU_LUT_ACCESS_CFG,
      reg(1, rk.DPU_LUT_ACCESS_CFG_LUT_ACCESS_TYPE__SHIFT, rk.DPU_LUT_ACCESS_CFG_LUT_ACCESS_TYPE__MASK) |
      reg(table_id, rk.DPU_LUT_ACCESS_CFG_LUT_TABLE_ID__SHIFT, rk.DPU_LUT_ACCESS_CFG_LUT_TABLE_ID__MASK) |
      reg(0, rk.DPU_LUT_ACCESS_CFG_LUT_ADDR__SHIFT, rk.DPU_LUT_ACCESS_CFG_LUT_ADDR__MASK)))
    for i in range(LUT_SIZE):
      v = int(lut[base + i])
      data = reg(v & 0xffff, rk.DPU_LUT_ACCESS_DATA_LUT_ACCESS_DATA__SHIFT,
                 rk.DPU_LUT_ACCESS_DATA_LUT_ACCESS_DATA__MASK)
      if v < 0:
        data |= reg(0xffff, rk.DPU_LUT_ACCESS_DATA_RESERVED_0__SHIFT,
                    rk.DPU_LUT_ACCESS_DATA_RESERVED_0__MASK)
      regs.append(emit(rk.DPU, rk.REG_DPU_LUT_ACCESS_DATA, data))
  return regs


def pack_f16(buf, vals):
  arr = np.asarray(vals, dtype=np.float16).view(np.uint16)
  (ctypes.c_uint16 * len(arr)).from_buffer(buf)[:] = arr.tolist()


def read_f16(buf, n):
  return np.frombuffer(buf, dtype=np.float16, count=n).copy()


def silu_regs(n, input_dma=0x11110000, output_dma=0x22220000):
  lut, bn_mul_operand, output_scale, index_scale = make_silu_lut()
  # rknnops.h's SiLU path uses one 16x8 DPU tile regardless of the requested
  # logical element count. The caller reads only the first n outputs.
  width = 15
  regs = fill_lut_regs(lut)

  regs += [
    emit(rk.DPU, rk.REG_DPU_S_POINTER,
      reg(1, rk.DPU_S_POINTER_EXECUTER_PP_CLEAR__SHIFT, rk.DPU_S_POINTER_EXECUTER_PP_CLEAR__MASK) |
      reg(1, rk.DPU_S_POINTER_POINTER_PP_CLEAR__SHIFT, rk.DPU_S_POINTER_POINTER_PP_CLEAR__MASK)),
    emit(rk.DPU_RDMA, rk.REG_DPU_RDMA_RDMA_S_POINTER,
      reg(1, rk.DPU_RDMA_RDMA_S_POINTER_EXECUTER_PP_CLEAR__SHIFT,
          rk.DPU_RDMA_RDMA_S_POINTER_EXECUTER_PP_CLEAR__MASK) |
      reg(1, rk.DPU_RDMA_RDMA_S_POINTER_POINTER_PP_CLEAR__SHIFT,
          rk.DPU_RDMA_RDMA_S_POINTER_POINTER_PP_CLEAR__MASK)),
    emit(rk.DPU, rk.REG_DPU_FEATURE_MODE_CFG,
      reg(15, rk.DPU_FEATURE_MODE_CFG_BURST_LEN__SHIFT, rk.DPU_FEATURE_MODE_CFG_BURST_LEN__MASK) |
      reg(2, rk.DPU_FEATURE_MODE_CFG_OUTPUT_MODE__SHIFT, rk.DPU_FEATURE_MODE_CFG_OUTPUT_MODE__MASK) |
      reg(1, rk.DPU_FEATURE_MODE_CFG_FLYING_MODE__SHIFT, rk.DPU_FEATURE_MODE_CFG_FLYING_MODE__MASK)),
    emit(rk.DPU, rk.REG_DPU_DATA_FORMAT,
      reg(2, rk.DPU_DATA_FORMAT_OUT_PRECISION__SHIFT, rk.DPU_DATA_FORMAT_OUT_PRECISION__MASK) |
      reg(2, rk.DPU_DATA_FORMAT_IN_PRECISION__SHIFT, rk.DPU_DATA_FORMAT_IN_PRECISION__MASK) |
      reg(2, rk.DPU_DATA_FORMAT_PROC_PRECISION__SHIFT, rk.DPU_DATA_FORMAT_PROC_PRECISION__MASK)),
    emit(rk.DPU, rk.REG_DPU_DST_BASE_ADDR,
      reg(output_dma, rk.DPU_DST_BASE_ADDR_DST_BASE_ADDR__SHIFT, rk.DPU_DST_BASE_ADDR_DST_BASE_ADDR__MASK)),
    emit(rk.DPU, rk.REG_DPU_DST_SURF_STRIDE,
      reg(16, rk.DPU_DST_SURF_STRIDE_DST_SURF_STRIDE__SHIFT, rk.DPU_DST_SURF_STRIDE_DST_SURF_STRIDE__MASK)),
    emit(rk.DPU, rk.REG_DPU_DATA_CUBE_WIDTH,
      reg(width, rk.DPU_DATA_CUBE_WIDTH_WIDTH__SHIFT, rk.DPU_DATA_CUBE_WIDTH_WIDTH__MASK)),
    emit(rk.DPU, rk.REG_DPU_DATA_CUBE_CHANNEL,
      reg(7, rk.DPU_DATA_CUBE_CHANNEL_ORIG_CHANNEL__SHIFT, rk.DPU_DATA_CUBE_CHANNEL_ORIG_CHANNEL__MASK) |
      reg(7, rk.DPU_DATA_CUBE_CHANNEL_CHANNEL__SHIFT, rk.DPU_DATA_CUBE_CHANNEL_CHANNEL__MASK)),
    emit(rk.DPU, rk.REG_DPU_BS_CFG,
      reg(1, rk.DPU_BS_CFG_BS_RELU_BYPASS__SHIFT, rk.DPU_BS_CFG_BS_RELU_BYPASS__MASK) |
      reg(1, rk.DPU_BS_CFG_BS_MUL_BYPASS__SHIFT, rk.DPU_BS_CFG_BS_MUL_BYPASS__MASK) |
      reg(1, rk.DPU_BS_CFG_BS_ALU_BYPASS__SHIFT, rk.DPU_BS_CFG_BS_ALU_BYPASS__MASK) |
      reg(1, rk.DPU_BS_CFG_BS_BYPASS__SHIFT, rk.DPU_BS_CFG_BS_BYPASS__MASK)),
    emit(rk.DPU, rk.REG_DPU_BS_OW_CFG,
      reg(1, rk.DPU_BS_OW_CFG_OD_BYPASS__SHIFT, rk.DPU_BS_OW_CFG_OD_BYPASS__MASK)),
    emit(rk.DPU, rk.REG_DPU_WDMA_SIZE_0,
      reg(7, rk.DPU_WDMA_SIZE_0_CHANNEL_WDMA__SHIFT, rk.DPU_WDMA_SIZE_0_CHANNEL_WDMA__MASK)),
    emit(rk.DPU, rk.REG_DPU_WDMA_SIZE_1,
      reg(width, rk.DPU_WDMA_SIZE_1_WIDTH_WDMA__SHIFT, rk.DPU_WDMA_SIZE_1_WIDTH_WDMA__MASK)),
    emit(rk.DPU, rk.REG_DPU_BN_CFG,
      reg(2, rk.DPU_BN_CFG_BN_ALU_ALGO__SHIFT, rk.DPU_BN_CFG_BN_ALU_ALGO__MASK) |
      reg(1, rk.DPU_BN_CFG_BN_RELU_BYPASS__SHIFT, rk.DPU_BN_CFG_BN_RELU_BYPASS__MASK)),
    emit(rk.DPU, rk.REG_DPU_BN_ALU_CFG, 0x80000000),
    emit(rk.DPU, rk.REG_DPU_BN_MUL_CFG,
      reg(bn_mul_operand, rk.DPU_BN_MUL_CFG_BN_MUL_OPERAND__SHIFT,
          rk.DPU_BN_MUL_CFG_BN_MUL_OPERAND__MASK)),
    emit(rk.DPU, rk.REG_DPU_EW_CFG,
      reg(1, rk.DPU_EW_CFG_EW_RELU_BYPASS__SHIFT, rk.DPU_EW_CFG_EW_RELU_BYPASS__MASK) |
      reg(1, rk.DPU_EW_CFG_EW_OP_CVT_BYPASS__SHIFT, rk.DPU_EW_CFG_EW_OP_CVT_BYPASS__MASK) |
      reg(1, rk.DPU_EW_CFG_EW_OP_BYPASS__SHIFT, rk.DPU_EW_CFG_EW_OP_BYPASS__MASK)),
    emit(rk.DPU, rk.REG_DPU_EW_CVT_SCALE_VALUE,
      reg(1, rk.DPU_EW_CVT_SCALE_VALUE_EW_OP_CVT_SCALE__SHIFT,
          rk.DPU_EW_CVT_SCALE_VALUE_EW_OP_CVT_SCALE__MASK)),
    emit(rk.DPU, rk.REG_DPU_OUT_CVT_SCALE,
      reg(1, rk.DPU_OUT_CVT_SCALE_FP32TOFP16_EN__SHIFT, rk.DPU_OUT_CVT_SCALE_FP32TOFP16_EN__MASK) |
      reg(1, rk.DPU_OUT_CVT_SCALE_OUT_CVT_SCALE__SHIFT, rk.DPU_OUT_CVT_SCALE_OUT_CVT_SCALE__MASK)),
    emit(rk.DPU, rk.REG_DPU_SURFACE_ADD,
      reg(32, rk.DPU_SURFACE_ADD_SURF_ADD__SHIFT, rk.DPU_SURFACE_ADD_SURF_ADD__MASK)),
    emit(0x1000, 0x40c4, 0),
    emit(rk.DPU, rk.REG_DPU_LUT_CFG,
      reg(1, rk.DPU_LUT_CFG_LUT_HYBRID_PRIORITY__SHIFT, rk.DPU_LUT_CFG_LUT_HYBRID_PRIORITY__MASK) |
      reg(1, rk.DPU_LUT_CFG_LUT_OFLOW_PRIORITY__SHIFT, rk.DPU_LUT_CFG_LUT_OFLOW_PRIORITY__MASK) |
      reg(2, rk.DPU_LUT_CFG_LUT_LO_LE_MUX__SHIFT, rk.DPU_LUT_CFG_LUT_LO_LE_MUX__MASK)),
    emit(rk.DPU, rk.REG_DPU_LUT_INFO,
      reg(5, rk.DPU_LUT_INFO_LUT_LO_INDEX_SELECT__SHIFT, rk.DPU_LUT_INFO_LUT_LO_INDEX_SELECT__MASK) |
      reg(5, rk.DPU_LUT_INFO_LUT_LE_INDEX_SELECT__SHIFT, rk.DPU_LUT_INFO_LUT_LE_INDEX_SELECT__MASK)),
    emit(rk.DPU, rk.REG_DPU_LUT_LE_START,
      reg(0xffffc000, rk.DPU_LUT_LE_START_LUT_LE_START__SHIFT, rk.DPU_LUT_LE_START_LUT_LE_START__MASK)),
    emit(rk.DPU, rk.REG_DPU_LUT_LO_END,
      reg(0x00004000, rk.DPU_LUT_LO_END_LUT_LO_END__SHIFT, rk.DPU_LUT_LO_END_LUT_LO_END__MASK)),
    emit(rk.DPU, rk.REG_DPU_LUT_LO_SLOPE_SCALE,
      reg(16434, rk.DPU_LUT_LO_SLOPE_SCALE_LUT_LO_SLOPE_OFLOW_SCALE__SHIFT,
          rk.DPU_LUT_LO_SLOPE_SCALE_LUT_LO_SLOPE_OFLOW_SCALE__MASK)),
    emit(rk.DPU, rk.REG_DPU_LUT_LO_SLOPE_SHIFT,
      reg(13, rk.DPU_LUT_LO_SLOPE_SHIFT_LUT_LO_SLOPE_OFLOW_SHIFT__SHIFT,
          rk.DPU_LUT_LO_SLOPE_SHIFT_LUT_LO_SLOPE_OFLOW_SHIFT__MASK)),
    emit(rk.DPU_RDMA, rk.REG_DPU_RDMA_RDMA_DATA_CUBE_WIDTH,
      reg(width, rk.DPU_RDMA_RDMA_DATA_CUBE_WIDTH_WIDTH__SHIFT, rk.DPU_RDMA_RDMA_DATA_CUBE_WIDTH_WIDTH__MASK)),
    emit(rk.DPU_RDMA, rk.REG_DPU_RDMA_RDMA_DATA_CUBE_CHANNEL,
      reg(7, rk.DPU_RDMA_RDMA_DATA_CUBE_CHANNEL_CHANNEL__SHIFT, rk.DPU_RDMA_RDMA_DATA_CUBE_CHANNEL_CHANNEL__MASK)),
    emit(rk.DPU_RDMA, rk.REG_DPU_RDMA_RDMA_SRC_BASE_ADDR,
      reg(input_dma, rk.DPU_RDMA_RDMA_SRC_BASE_ADDR_SRC_BASE_ADDR__SHIFT,
          rk.DPU_RDMA_RDMA_SRC_BASE_ADDR_SRC_BASE_ADDR__MASK)),
    emit(rk.DPU_RDMA, rk.REG_DPU_RDMA_RDMA_ERDMA_CFG,
      reg(1, rk.DPU_RDMA_RDMA_ERDMA_CFG_ERDMA_DISABLE__SHIFT,
          rk.DPU_RDMA_RDMA_ERDMA_CFG_ERDMA_DISABLE__MASK)),
    emit(rk.DPU_RDMA, rk.REG_DPU_RDMA_RDMA_FEATURE_MODE_CFG,
      reg(2, rk.DPU_RDMA_RDMA_FEATURE_MODE_CFG_IN_PRECISION__SHIFT, rk.DPU_RDMA_RDMA_FEATURE_MODE_CFG_IN_PRECISION__MASK) |
      reg(15, rk.DPU_RDMA_RDMA_FEATURE_MODE_CFG_BURST_LEN__SHIFT, rk.DPU_RDMA_RDMA_FEATURE_MODE_CFG_BURST_LEN__MASK) |
      reg(2, rk.DPU_RDMA_RDMA_FEATURE_MODE_CFG_PROC_PRECISION__SHIFT, rk.DPU_RDMA_RDMA_FEATURE_MODE_CFG_PROC_PRECISION__MASK) |
      reg(1, rk.DPU_RDMA_RDMA_FEATURE_MODE_CFG_MRDMA_FP16TOFP32_EN__SHIFT, rk.DPU_RDMA_RDMA_FEATURE_MODE_CFG_MRDMA_FP16TOFP32_EN__MASK) |
      reg(1, rk.DPU_RDMA_RDMA_FEATURE_MODE_CFG_FLYING_MODE__SHIFT, rk.DPU_RDMA_RDMA_FEATURE_MODE_CFG_FLYING_MODE__MASK)),
    emit(rk.DPU_RDMA, rk.REG_DPU_RDMA_RDMA_WEIGHT,
      reg(1, rk.DPU_RDMA_RDMA_WEIGHT_E_WEIGHT__SHIFT, rk.DPU_RDMA_RDMA_WEIGHT_E_WEIGHT__MASK) |
      reg(1, rk.DPU_RDMA_RDMA_WEIGHT_N_WEIGHT__SHIFT, rk.DPU_RDMA_RDMA_WEIGHT_N_WEIGHT__MASK) |
      reg(1, rk.DPU_RDMA_RDMA_WEIGHT_B_WEIGHT__SHIFT, rk.DPU_RDMA_RDMA_WEIGHT_B_WEIGHT__MASK) |
      reg(1, rk.DPU_RDMA_RDMA_WEIGHT_M_WEIGHT__SHIFT, rk.DPU_RDMA_RDMA_WEIGHT_M_WEIGHT__MASK)),
    emit(rk.PC, rk.REG_PC_OPERATION_ENABLE, 0x18),
  ]
  return regs, lut, bn_mul_operand, output_scale, index_scale


def run_silu(n):
  fd = os.open("/dev/dri/card1", os.O_RDWR)
  try:
    reset_npu(fd)
    task_map, task_mc = mem_allocate(fd, 4096, RKNPU_MEM_KERNEL_MAPPING | RKNPU_MEM_NON_CACHEABLE)
    regcmd_map, regcmd_mc = mem_allocate(fd, 16384, RKNPU_MEM_NON_CACHEABLE)
    input_map, input_mc = mem_allocate(fd, 4096, RKNPU_MEM_NON_CACHEABLE)
    output_map, output_mc = mem_allocate(fd, 4096, RKNPU_MEM_NON_CACHEABLE)

    tasks = ctypes.cast(ctypes.addressof(ctypes.c_char.from_buffer(task_map)), ctypes.POINTER(struct_rknpu_task))
    regcmd = ctypes.cast(ctypes.addressof(ctypes.c_char.from_buffer(regcmd_map)), ctypes.POINTER(ctypes.c_uint64))

    x = np.linspace(-3.0, 3.0, n, dtype=np.float16)
    expected = (x.astype(np.float32) / (1.0 + np.exp(-x.astype(np.float32)))).astype(np.float16)
    pack_f16(input_map, x)
    output_map[: n * 2] = b"\x00" * (n * 2)

    regs, lut, bn_mul_operand, output_scale, index_scale = silu_regs(n, input_mc.dma_addr, output_mc.dma_addr)
    for i in range(len(regs)):
      regcmd[i] = regs[i]

    tasks[0].flags = 0
    tasks[0].op_idx = 4
    tasks[0].enable_mask = 0x18
    tasks[0].int_mask = 0x300
    tasks[0].int_clear = 0x1ffff
    tasks[0].int_status = 0
    tasks[0].regcfg_amount = len(regs)
    tasks[0].regcfg_offset = 0
    tasks[0].regcmd_addr = regcmd_mc.dma_addr

    ret = submit(fd, task_mc.obj_addr)
    got = read_f16(output_map, n)
    decoded = (got.astype(np.float32) / output_scale).astype(np.float16)
    ok = ret == 0 and np.allclose(decoded, expected, atol=0.01)
    print(f"SUBMIT ret={ret}")
    print(f"input={x}")
    print(f"NPU raw={got}")
    print(f"NPU decoded={decoded}")
    print(f"expected={expected}")
    print("SILU PASS" if ok else "SILU FAIL")
    return 0 if ok else 1
  finally:
    os.close(fd)


def main():
  parser = argparse.ArgumentParser(description="Dry-run RK3588 NPU SiLU LUT register stream")
  parser.add_argument("--n", type=int, default=8, help="number of fp16 elements")
  parser.add_argument("--submit", action="store_true", help="run the register stream on the NPU")
  args = parser.parse_args()

  if args.submit:
    return run_silu(args.n)

  x = np.linspace(-3.0, 3.0, args.n, dtype=np.float16)
  expected = (x.astype(np.float32) / (1.0 + np.exp(-x.astype(np.float32)))).astype(np.float16)
  regs, lut, bn_mul_operand, output_scale, index_scale = silu_regs(args.n)

  print("SiLU dry run only: no /dev/dri open, no ioctl, no submit")
  print(f"elements={args.n} reg_count={len(regs)} lut_entries={len(lut)}")
  print(f"index_scale={index_scale:.6f} bn_mul_operand=0x{bn_mul_operand & 0xffff:04x} output_scale={output_scale:.6f}")
  print(f"input={x}")
  print(f"cpu_expected={expected}")
  print("first_regs:")
  for value in regs[:8]: print(f"  0x{value:016x}")
  print("last_regs:")
  for value in regs[-8:]: print(f"  0x{value:016x}")
  print("SILU DRY RUN PASS")
  return 0


if __name__ == "__main__":
  raise SystemExit(main())
